"""empty message

Revision ID: 3e7bd61d7ae8
Revises: 88bdc994ecf6
Create Date: 2022-12-25 10:23:59.962180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e7bd61d7ae8'
down_revision = '88bdc994ecf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('area_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('areaname', sa.String(length=20), nullable=False),
    sa.Column('area_range', sa.Float(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('area_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.drop_table('area')
    # ### end Alembic commands ###
