"""empty message

Revision ID: 88bdc994ecf6
Revises: 
Create Date: 2022-12-23 10:28:02.413510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88bdc994ecf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    op.create_table('data',
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('order_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('money', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('province', mysql.VARCHAR(charset='utf8', length=10), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
