"""empty message

Revision ID: 97103249831d
Revises: 3e7bd61d7ae8
Create Date: 2022-12-25 17:32:01.291565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97103249831d'
down_revision = '3e7bd61d7ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fellow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fellow_name', sa.String(length=20), nullable=False),
    sa.Column('fellow_phone', sa.String(length=20), nullable=False),
    sa.Column('fellow_sex', sa.String(length=30), nullable=False),
    sa.Column('fellow_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fellow_sex')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('area_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=20),
               nullable=False)
        batch_op.alter_column('money',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('money',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('area_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=20),
               nullable=True)

    op.drop_table('fellow')
    # ### end Alembic commands ###
