"""empty message

Revision ID: aceb1b97e466
Revises: 97103249831d
Create Date: 2022-12-25 19:01:52.598988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceb1b97e466'
down_revision = '97103249831d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('fellow', sa.Integer(), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_data',
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_data')
    op.drop_table('data')
    # ### end Alembic commands ###
