"""empty message

Revision ID: e1c934d51906
Revises: aceb1b97e466
Create Date: 2022-12-25 19:22:13.178814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1c934d51906'
down_revision = 'aceb1b97e466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_data')
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_area', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('data_area')

    op.create_table('area_data',
    sa.Column('area_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_croatian_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
